### ISSUE TITLE
Request: Ignore user

### ISSUE THREAD

**Issue by vitorgalvao** [deanishe/alfred-packal-search#2]
More specifically, I’d like the possibility to ignore myself. Since I don’t use my own packal versions on Alfred, I end up with a list like this when searching for updates:
![](http://i.imgur.com/vZKveDr.png)

I was under the impression this had been discussed on the forums, but couldn’t find it.

**Comment by deanishe** [comment]
I think it was discussed, but in the thread for the official Packal updater. I didn't think anyone still used this 'un, but in hindsight I guess the official updater isn't your kind of workflow :wink: 

It's definitely a useful feature, and I've added the it in [v1.3](https://github.com/deanishe/alfred-packal-search/releases/tag/v1.3).

In the `packal authors` list, use `⌘+↩` to "blacklist" an author, so their workflows are excluded from the update status list.

**Comment by vitorgalvao** [comment]
Thank you. I really appreciate it (you are very much correct regarding me and the official updater). I use this regularly, and opening it just once after updating it already made clear how much easier it’ll be to find updates.

**Comment by deanishe** [comment]
To be perfectly honest, that's the main reason I never used my own workflow. It is much more useful now.
