### ISSUE TITLE
stuck in the updating message

### ISSUE THREAD

**Issue by sdaza** [deanishe/alfred-packal-search#3]
I get stuck in the _updating from packal..._ message. After that, nothing happens: 

```
Starting debug for 'Packal Search'

[STDERR: alfred.workflow.input.scriptfilter] 08:12:06 workflow.py:1972 DEBUG    Workflow version : 1.3.0
08:12:06 packal.py:152 DEBUG    0 workflows in cache
08:12:06 packal.py:369 DEBUG    Updating workflow lists...
08:12:06 packal.py:374 DEBUG    update command : [u'/usr/bin/python', u'/Users/sdaza/Dropbox/Alfred/Alfred.alfredpreferences/workflows/user.workflow.60980A2B-F90D-4BBB-B272-D300CB0254C2/update_workflows.py']
08:12:06 background.py:188 DEBUG    Command arguments cached to `/Users/sdaza/Library/Caches/com.runningwithcrayons.Alfred-2/Workflow Data/net.deanishe.alfred-packal-search/update.argcache`
08:12:06 background.py:192 DEBUG    Calling [u'/usr/bin/python', '/Users/sdaza/Dropbox/Alfred/Alfred.alfredpreferences/workflows/user.workflow.60980A2B-F90D-4BBB-B272-D300CB0254C2/workflow/background.pyc', u'update'] ...
08:12:06 workflow.py:1972 DEBUG    Workflow version : 1.3.0
08:12:06 workflow.py:2008 DEBUG    Workflow finished in 0.018 seconds.
08:12:06 workflow.py:2008 DEBUG    Workflow finished in 0.019 seconds.
08:12:06 background.py:197 DEBUG    Executing task `update` in background...
08:12:06 workflow.py:1387 DEBUG    Reading settings from `/Users/sdaza/Library/Application Support/Alfred 2/Workflow Data/net.deanishe.alfred-packal-search/settings.json` ...
08:12:06 workflow.py:2163 DEBUG    Set last run version : 1.3.0
08:12:06 workflow.py:2008 DEBUG    Workflow finished in 0.101 seconds.
[STDERR: alfred.workflow.input.scriptfilter] 08:12:08 workflow.py:1972 DEBUG    Workflow version : 1.3.0
08:12:08 packal.py:152 DEBUG    0 workflows in cache
08:12:08 packal.py:369 DEBUG    Updating workflow lists...
08:12:08 packal.py:374 DEBUG    update command : [u'/usr/bin/python', u'/Users/sdaza/Dropbox/Alfred/Alfred.alfredpreferences/workflows/user.workflow.60980A2B-F90D-4BBB-B272-D300CB0254C2/update_workflows.py']
08:12:08 background.py:188 DEBUG    Command arguments cached to `/Users/sdaza/Library/Caches/com.runningwithcrayons.Alfred-2/Workflow Data/net.deanishe.alfred-packal-search/update.argcache`
08:12:08 background.py:192 DEBUG    Calling [u'/usr/bin/python', '/Users/sdaza/Dropbox/Alfred/Alfred.alfredpreferences/workflows/user.workflow.60980A2B-F90D-4BBB-B272-D300CB0254C2/workflow/background.pyc', u'update'] ...
08:12:08 workflow.py:1972 DEBUG    Workflow version : 1.3.0
08:12:08 workflow.py:2008 DEBUG    Workflow finished in 0.017 seconds.
08:12:08 workflow.py:2008 DEBUG    Workflow finished in 0.018 seconds.
08:12:08 background.py:197 DEBUG    Executing task `update` in background...
08:12:08 workflow.py:1387 DEBUG    Reading settings from `/Users/sdaza/Library/Application Support/Alfred 2/Workflow Data/net.deanishe.alfred-packal-search/settings.json` ...
08:12:08 workflow.py:2163 DEBUG    Set last run version : 1.3.0
08:12:08 workflow.py:2008 DEBUG    Workflow finished in 0.097 seconds.
```

**Comment by deanishe** [comment]
As you can see from the log, the workflow is finished. The _updating from Packal…_ message is for information purposes only. It doesn't mean the workflow is still running. It isn't (the update happens in the background).

When you see that message, just keep using the workflow. It will use the old data (if there are any) until the update is complete. Your next query after that will be run against the new data.

As with any workflow, if it's already showing any result, it has finished running, and nothing will change until you change the query (which will run the workflow again).

**Comment by sdaza** [comment]
The thing is that I don't get anything from the workflow when I just keep using it.

**Comment by sdaza** [comment]
I get this: 

[ERROR: alfred.workflow.action.script] 20:14:04 workflow.py:1972 DEBUG    Workflow version : 1.3.0
20:14:04 packal.py:152 DEBUG    0 workflows in cache
20:14:04 packal.py:369 DEBUG    Updating workflow lists...
20:14:04 packal.py:374 DEBUG    update command : [u'/usr/bin/python', u'/Users/sdaza/Dropbox/Alfred/Alfred.alfredpreferences/workflows/user.workflow.60980A2B-F90D-4BBB-B272-D300CB0254C2/update_workflows.py']
20:14:04 background.py:188 DEBUG    Command arguments cached to `/Users/sdaza/Library/Caches/com.runningwithcrayons.Alfred-2/Workflow Data/net.deanishe.alfred-packal-search/update.argcache`
20:14:04 background.py:192 DEBUG    Calling [u'/usr/bin/python', '/Users/sdaza/Dropbox/Alfred/Alfred.alfredpreferences/workflows/user.workflow.60980A2B-F90D-4BBB-B272-D300CB0254C2/workflow/background.pyc', u'update'] ...
20:14:04 workflow.py:1972 DEBUG    Workflow version : 1.3.0
20:14:04 workflow.py:2008 DEBUG    Workflow finished in 0.021 seconds.
20:14:04 workflow.py:2008 DEBUG    Workflow finished in 0.023 seconds.
20:14:04 background.py:197 DEBUG    Executing task `update` in background...
20:14:04 workflow.py:1387 DEBUG    Reading settings from `/Users/sdaza/Library/Application Support/Alfred 2/Workflow Data/net.deanishe.alfred-packal-search/settings.json` ...
20:14:04 workflow.py:2163 DEBUG    Set last run version : 1.3.0
20:14:04 workflow.py:2008 DEBUG    Workflow finished in 0.207 seconds.
